### ISSUE TITLE
create docker-compose file & update dockerfile - for rapid test/production deployment

### ISSUE THREAD

**Issue by mobidev111** [nijel/weblate#808]
docker-compose combines the whole setup (database, weblate app, etc.) - and the weblate app is up in seconds without any configuration - a major plus for new users.

Examples for setting up docker-compose for django & databases are here:
https://docs.docker.com/compose/django/
https://realpython.com/blog/python/django-development-with-docker-compose-and-machine/

I tried the docker file from @wichert https://github.com/wichert/docker-weblate as mentioned in https://github.com/nijel/weblate/issues/618 - however, in the end working out a connected database connection is crucial.

A first shot at the docker-compose.yml is this:
(move the wichert/docker-weblate folder in)

directory structure:
- docker-compose.yml
- weblate-web - files from wichert/docker-weblate

```
weblate-web:
  build: weblate-web
  links:
    - weblate-db
  ports:
    - "8000:8000"
  volumes:
    - weblate-web:/app/etc
    - weblate-web:/app/data
  volumes_from:
    - weblate-logs-volume
    - weblate-storage-volume
weblate-logs-volume:
  image: busybox
  volumes:
    - /logs
weblate-storage-volume:
  image: busybox
  volumes:
    - /storage
weblate-db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=weblate
    - MYSQL_USER=weblate
    - MYSQL_PASSWORD=weblate
    - MYSQL_DATABASE=weblatedb
  volumes_from:
    - weblate-db-volume
weblate-db-volume:
  image: busybox
  volumes:
    - /var/lib/mysql
```

the settings.py database connection settings are as follows:
```
DATABASES = {
    'default': {
        # Use 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'ENGINE': 'django.db.backends.mysql',
        # Database name or path to database file if using sqlite3.
        'NAME': 'weblatedb',
        # Database user, not used with sqlite3.
        'USER': 'root',
        # Database password, not used with sqlite3.
        'PASSWORD': 'weblate',
        # Set to empty string for localhost. Not used with sqlite3.
        'HOST': 'weblate-db',
        # Set to empty string for default. Not used with sqlite3.
        'PORT': '3306',
    }
}
```

The database connection still seems to not work fully - it connects, but the users need to be configured accordingly. 

@wichert @nijel How does this look like to you? any others interested to drive this further?
